services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    # restart: always
    env_file:
      - path: .env
        required: true
    volumes:
      - database:/home/jvigny/data
    ports:
      - '3306:3306'
  # wordpress:
  #   build: ./requirements/wordpres/
  #   volume:
  #     - wordpress: /home/jvigny/data
  # nginx:
  #   build: ./requirements/nginx/
  #   volume:
  #     - wordpress: /home/jvigny/data

volumes:
  database:
  # wordpress:
