services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    # image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - database:/var/lib/mysql
    expose:
      - 3306
    networks:
      - my_network

  wordpress:
    container_name: wordpress
    image: wordpress:latest
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
    restart: always
    ports:
      - '8080:80'
    networks:
      - my_network


volumes:
  database:
    name: database
    driver: local
    driver_opts:
      device: /home/jvigny/data/database
      type: none
      o: bind
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/jvigny/data/wordpress
      type: none
      o: bind

networks:
  my_network:
    name: my_network
    driver: bridge


  # nginx:
  #   container_name: nginx
  #   image: nginx:latest
  #   restart: always
  #   depends_on:
  #     - wordpress
  #   volumes:
  #     - wordpress:/var/www/html
  #     # - ./nginx:/etc/nginx/conf.d
  #   ports:
  #     - '80:80'
  #   networks:
  #     - my_network
  #   env_file:
  #     - path: .env
  #       required: true