services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    # restart: always
    env_file:
      - path: .env
        required: true
    volumes:
      - database:/home/jvigny/data
    ports:
      - '3306:3306'
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    volumes:
      - wordpress:/home/jvigny/data
    ports:
      - '9000:9000'
    env_file:
    - path: .env
      required: true
  # nginx:
  #   build: ./requirements/nginx/
  #   volume:
  #     - wordpress: /home/jvigny/data

volumes:
  database:
  wordpress:
