services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    env_file:
      - path: .env
        required: true
    volumes:
      - database:/home/jvigny/data
    ports:
      - '3306:3306'

  wordpress:
    container_name: wordpress
    image: wordpress:latest
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/htlm
    ports:
      - '9000:9000'
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
    # env_file:
    #   - path: .env
    #     required: true
    restart: always


  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - wordpress
    volumes:
      - wordpress:/home/jvigny/data
    ports:
      - '80:80'
    restart: always
    # environment:
    #   - NGINX_HOST=jvigny.42.fr
    #   - NGINX_PORT=443

volumes:
  database:
  wordpress: